package h_exception;

import java.io.IOException;
import java.util.Scanner;

import e_oop.ScanUtil;

public class ThrowsException {

	public static void main(String[] args) {
		
		System.out.println("숫자입력>");
		int nextInt = ScanUtil.nextInt();
		System.out.println("입력한 숫자: "+ nextInt);
		
		
//	}
//		try {
//			method();			
//		}catch(IOException e) {
//			e.printStackTrace();
//		}
//		
//		new NullPointerException();
//	
//		String str = null;
//		
//		System.out.println(str.equals("")); //어디에 null이 있는지, 객체생성을 안했는지 확인한다.
//		
//		
//		new IndexOutOfBoundsException();
//		//배열의 인덱스가 범위를 벗어났다.
//		int[] arr = new int[10];
//		arr[10] = 0;
//		
//	
//	}
//
//	
//	
//	
//	private static void method() throws IOException {
//		//예외를 강제로 발생
//		throw new IOException();//발생한 예외가 생긴 위치에 객체가 생성된다.
//		
	}

}
